### ISSUE TITLE
Objects load as "before" not "after" in object view

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/First-Responders#29] opened 2015-01-13 16:25 UTC
Given that objects on First Responders display as thumbnails in the Recents page with the "after" view, and given that the "after" view is the pertinent one, objects should appear first in their object pages with the "after" view, not the "before" view as they currently do.

Right?

**Comment by vrooje** [comment] 2015-01-13 18:25
This is a duplicate of #21 .

**Closed by vrooje** 2015-01-13 18:25 UTC
Labels: enhancement
